

services:
  postgres:
    image: "postgres"
    container_name: files_keeper
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretKeyPostgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: files_keeper
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - files-keeper-network
    restart: unless-stopped

networks:
  files-keeper-network:
      driver: bridge

volumes:
  postgres:
    driver: local