services:
  postgres:
    container_name: postgres-files-keeper
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: files-keeper
    volumes:
      - postgres: data/postgres
    ports:
      - 5432:5432
    networks:
      - files-keeper
    restart: unless-stopped

#  mail-dev:
#    container_name: mail-dev
#    image: maildev/maildev
#    ports:
#      - 1080:1080
#      - 1025:1025


volumes:
  postgres:
    driver: local

networks:
  files-keeper:
    driver: bridge
