spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/files_keeper
    username: postgres
    password: badiro12
    driver-class-name: org.postgresql.Driver
    dbcp2:
      default-auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: hasanalmunawar01@gmail.com
    password: vhpmeizmdpvpiclz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    org:
      springframework:
        security: trace

springdoc:
  api-docs:
    path: /api-docs

#paypal:
#  client-id: <CLIENT-ID>
#  client-secret: <CLIENT-SECRET>
#  mode: sandbox

#spring:
#  profiles:
#    active: dev
#  servlet:
#    multipart:
#      max-file-size: 50MB
#
#springdoc:
#  default-produces-media-type: application/json

#server:
#  servlet:
#    context-path: "/api/v1"

